# Generated by Django 4.0.4 on 2022-05-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_dt', models.DateTimeField()),
                ('arrival_dt', models.DateTimeField()),
                ('departure_point', models.CharField(max_length=255)),
                ('arrival_point', models.CharField(max_length=255)),
                ('cargo_volume', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['departure_point'],
            },
        ),
    ]
