# Generated by Django 4.0.4 on 2022-05-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"ordering": ["departure_dt"]},
        ),
    ]
